#!/bin/bash
TDIR=$(mktemp -d)
LOCAL_DIR=/usr/local/bin

URL=https://github.com/bluemix-enablement/CodeSnippets/trunk/scriptupdates/

if [ "$EUID" -ne 0 ]
  then echo "Script should be run as root"
  exit
fi

echo Downloading updated scripts from $URL to $TDIR
svn export --force $URL $TDIR
pushd $TDIR
chmod +x *
mv -v * $LOCAL_DIR
popd
rmdir $TDIR

