#!/bin/bash
TDIR=$(mktemp -d)
LOCAL_DIR=/usr/local/bin
LOCAL_FILE_NAME=$LOCAL_DIR/$FILE_NAME

OLD_FILE_NAME=$LOCAL_FILE_NAME.old

URL=https://github.com/bluemix-enablement/CodeSnippets/trunk/scriptupdates/

if [ "$EUID" -ne 0 ]
  then echo "Script should be run as root"
  exit
fi

echo Downloading updated scripts from $URL to $TDIR
svn export --force $URL $TDIR
pushd $TDIR
chmod +x *
mv -v * /usr/local/bin/
popd
rmdir $TDIR

